name: Security Audit

on:
  pull_request:
    paths:
      - 'contracts/**'
      - 'src/**'

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Run MythX analysis
        uses: mythx-cli/mythx-action@v1
        env:
          MYTHX_API_KEY: ${{ secrets.MYTHX_API_KEY }}
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
