name: Smart Contract Security Audit

on:
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Slither
        run: pip3 install slither-analyzer
      
      - name: Run Slither
        run: slither contracts/

      - name: Run MythX Analysis
        uses: MythX/mythx-action@v1
        with:
          api-key: ${{ secrets.MYTHX_API_KEY }}
          contracts: 'contracts/'
          mode: standard

      - name: Run Certora Verification
        uses: Certora/certora-action@v1
        with:
          api-key: ${{ secrets.CERTORA_API_KEY }}
          spec: 'specs/verify.spec'
