name: Smart Contract Security Audit

on:
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Slither
        run: pip3 install slither-analyzer
      
      - name: Run Slither
        run: slither contracts/

      - name: Run MythX CLI Analysis
        run: |
          npm install -g mythx-cli
          mythx --api-key ${{ secrets.MYTHX_API_KEY }} analyze contracts/
        env:
          MYTHX_API_KEY: ${{ secrets.MYTHX_API_KEY }}

      - name: Install Certora CLI
        run: |
          pip3 install certora-cli
          
      - name: Run Certora Verification
        run: |
          certoraRun specs/verify.spec \
            --solc solc8.0 \
            --path contracts/ \
            --settings -t=600
        env:
          CERTORAKEY: ${{ secrets.CERTORA_API_KEY }}

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-results
          path: |
            slither-results.json
            mythx-results.json
            certora-results.json
